#!/usr/bin/env python3
"""Generate firmware/arduino/version.h from git state.

Usage: python firmware/scripts/gen_version_h.py
Writes firmware/arduino/version.h with KRABBY_FW_VERSION, BRANCH, COMMIT.
"""
import subprocess
from pathlib import Path

TEMPLATE = """\
#pragma once
// Generated by CI — do not edit by hand.
#define KRABBY_FW_VERSION "{version}"
#define KRABBY_FW_BRANCH "{branch}"
#define KRABBY_FW_COMMIT "{commit}"
"""

_SCRIPTS_DIR = Path(__file__).parent


def _git(cmd: list) -> str:
    return subprocess.check_output(cmd, text=True).strip()


def derive_version(branch: str) -> str:
    """Extract semver from release/* branches; use branch name otherwise."""
    if branch.startswith("release/"):
        return branch.split("/", 1)[1]
    return branch


def render(version: str, branch: str, commit: str) -> str:
    return TEMPLATE.format(version=version, branch=branch, commit=commit)


def main(output: Path | None = None) -> None:
    branch = _git(["git", "rev-parse", "--abbrev-ref", "HEAD"])
    commit = _git(["git", "rev-parse", "--short=7", "HEAD"])
    version = derive_version(branch)
    dest = output or (_SCRIPTS_DIR.parents[0] / "arduino" / "version.h")
    dest.write_text(render(version, branch, commit))
    print(f"Wrote {dest}  version={version}  branch={branch}  commit={commit}")


if __name__ == "__main__":
    main()
