import textwrap
import pytest

from firmware.scripts.gen_version_h import derive_version, render


class TestDeriveVersion:
    def test_release_branch_extracts_semver(self):
        assert derive_version("release/0.2.0") == "0.2.0"

    def test_release_branch_with_prerelease(self):
        assert derive_version("release/1.0.0-rc1") == "1.0.0-rc1"

    def test_mainline_returns_mainline(self):
        assert derive_version("mainline") == "mainline"

    def test_arbitrary_branch_returns_branch_name(self):
        assert derive_version("feat/some-feature") == "feat/some-feature"


class TestRender:
    def test_golden_release(self):
        expected = textwrap.dedent("""\
            #pragma once
            // Generated by CI — do not edit by hand.
            #define KRABBY_FW_VERSION "0.2.0"
            #define KRABBY_FW_BRANCH "release/0.2.0"
            #define KRABBY_FW_COMMIT "abc1234"
        """)
        assert render("0.2.0", "release/0.2.0", "abc1234") == expected

    def test_golden_mainline(self):
        expected = textwrap.dedent("""\
            #pragma once
            // Generated by CI — do not edit by hand.
            #define KRABBY_FW_VERSION "mainline"
            #define KRABBY_FW_BRANCH "mainline"
            #define KRABBY_FW_COMMIT "def5678"
        """)
        assert render("mainline", "mainline", "def5678") == expected

    def test_output_contains_pragma_once(self):
        assert render("1.0", "mainline", "abc0000").startswith("#pragma once\n")

    def test_special_chars_in_branch_preserved(self):
        out = render("1.0.0-rc1", "release/1.0.0-rc1", "abc1234")
        assert '#define KRABBY_FW_BRANCH "release/1.0.0-rc1"' in out
